### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/ldproxy#438]
- [x] interactive-instruments/ldproxy-project-management#109
- [x] interactive-instruments/ldproxy-project-management#110
- [x] interactive-instruments/xtraserver-webapi#53

**Comment by azahnen** [comment]
Closing, the issues are either fixed or no longer relevant.
