### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by azahnen** [interactive-instruments/ldproxy#717]
Currently only a very basic access control is available that restricts access to writing operations to authenticated users.
This epic proposes a concept for fine-grained access control mechanisms that cover all known use cases.

- [x] **all operations** (#718)
  This introduces the option to restrict access to `GET` operations in addition to writing operations. It also introduces the roles `read` and `write` which users need to have to access the corresponding operations.

- [x] **auth flow integration** (#721)
  This will integrate html views and swagger ui with the authentication flow of the identity provider.

- [x] **role based access control** (#720)
  This will introduce more roles that will allow fine-grained access control to APIs, collections and single operations.

- [x] **attribute based access control** (#722)
  This will extend the existing XACML support to cover more use cases. It will introduce means to access feature properties that are not part of the request in policies and add support for obligations to filter responses.

- [x] **audience claims** (#925)
  This will add an option to only accept tokens intended for the configured audience.
